version: '3'

services:
  chatbot:
    image: lenchq/rzd_chatbot:latest
    restart: 'on-failure'
    build:
      context: .
    environment:
       - 'DOTNET_ENVIRONMENT=PRODUCTION'
    depends_on:
      - redis
      - pg
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rzd
        
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=
    restart: 'on-failure'
    networks:
      - rzd
  
  pg:
    image: bitnami/postgresql:latest
    restart: 'on-failure'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    networks:
      - rzd 
        
volumes:
  postgresql_data:
    driver: local

networks:
  rzd:
    driver: bridge